#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

exec >/dev/tty 2>&1
pushd ./StudyPlannerUI > /dev/null

echo "Linting staged files... (UI)"
FORCE_COLOR=1 npx lint-staged

echo "Building React app... (UI)"
pnpm run build

popd > /dev/null
echo "Checking License headers..."
license-eye -c .github/license-eye.yml header fix
exit_code=$?

echo "The exit code of license-eye is $exit_code"
