# Copyright Andreas Bartilson & Pontus Salenbo 2023-2024
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the included LICENSE file for
# the full text of the GNU General Public License.

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: StudyPlannerAPI/Dockerfile.dev
    ports:
      - "5085:5085"
      - "7266:7266"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_URL=postgress://postgres:secret@db:5432/studyplanner
    volumes:
      - ./StudyPlannerAPI:/backend
      - ~/.nuget/packages:/root/.nuget/packages
      - ~/.aspnet/https:/https
    command: ["dotnet", "watch", "run"]
  frontend:
    build:
      context: .
      dockerfile: StudyPlannerUI/Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./StudyPlannerUI:/app
      - /app/node_modules