# Copyright Andreas Bartilson & Pontus Salenbo 2023-2024
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the included LICENSE file for
# the full text of the GNU General Public License.

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: StudyPlannerAPI/Dockerfile
    volumes:
      - ./StudyPlannerAPI:/backend  # Mount the app directory
    environment:
      - PORT=5000
      - ASPNETCORE_URLS=http://*:$PORT
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: studyplanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    # env_file: .env
    depends_on:
      - db
    ports:
      - 5050:80

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge