# Copyright Andreas Bartilson & Pontus Salenbo 2023-2024
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the included LICENSE file for
# the full text of the GNU General Public License.

# Use the official image as a parent image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base

ENV ASPNETCORE_Kestrel__Certificates__Default__Password="secret"
ENV ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

# Set the working directory
WORKDIR /backend

# Copy the project file
COPY ["StudyPlannerAPI", "./"]

# Restore dependencies
RUN dotnet restore

# Start the app
CMD ["dotnet", "watch", "run"]
