name: CI/CD for React Application

permissions:
    contents: read
    pull-requests: write

on:
    push:
        branches: ['master']
        paths:
            - "StudyPlannerUI/src/**"
            - "StudyPlannerUI/public/**"
            - ".github/workflows/azure-static-web-app.yml"
            - "StudyPlannerUI/vite.config.ts"
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - master
        paths:
            - "StudyPlannerUI/src/**"
            - "StudyPlannerUI/public/**"
            - ".github/workflows/azure-static-web-app.yml"
            - "StudyPlannerUI/vite.config.ts"

    workflow_dispatch:


env:
    NPM_CONFIG_LEGACY_PEER_DEPS: true

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./StudyPlannerUI

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
                  cache-dependency-path: './StudyPlannerUI/pnpm-lock.yaml'
            - name: Install dependencies
              run: pnpm install
            - name: Build project
              run: pnpm run build
            - name: Upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: build-artifacts
                  path: StudyPlannerUI/build
        env:
            HUSKY: '0' # By default do not run HUSKY install

    deploy:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Download build artifacts
              uses: actions/download-artifact@v2
              with:
                  name: build-artifacts
                  path: StudyPlannerUI/build
            - name: Deploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_COAST_037526F03 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  app_location: '/StudyPlannerUI' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'build' # Built app content directory - optional
              env:
                  VERBOSE: true

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                app_location: '/StudyPlannerUI' # App source code path
                azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_COAST_037526F03 }}
                action: "close"